name: a-new-hope
method: bayes
metric:
  goal: minimize
  name: metric
early_terminate:
  type: hyperband
  max_iter: 300
  s: 2
  eta: 2

parameters:
  model:
    parameters:
      encoder_num_layers:
        min: 1
        max: 2
      use_grade_mixer_pga_interface:
        values: [True, False]
      virtual_nodes_init_distribution:
        values: [uniform, truncated_normal]
      virtual_s_channels:
        values: [64, 128]
  training:
    parameters:
      loss:
        values: [l1, mse]
      var_lr:
        min: 1e-4
        max: 1e-3

command:
- python
- scripts/arterial_surface.py
- training.num_epochs=300
- +wandb=True
