model:
  encoder_num_layers: 1  # case "vine_gatr"
  hidden_mv_channels: 8
  id: vine_gatr
  num_blocks: 10
  num_heads: 4
  num_virtual_nodes: 1000  # case "vine_gatr"
  use_grade_mixer_pga_interface: True  # case "vine_gatr"
  virtual_nodes_init_distribution: truncated_normal  # case "vine_gatr"
  virtual_nodes_use_orientation: False  # case "vine_gatr"
  virtual_s_channels: 64  # case "vine_gatr"

training:
  batch_size: 8
  loss: l1
  loss_term_factors:
    attractive: 0.
    generic: 1.
  lr: 3e-4
  lr_decay_factor: 0.9955
  num_epochs: ???
  var_lr: 3e-4
