model:
  hidden_mv_channels: 4
  id: gatr
  num_blocks: 4
  num_heads: 4

num_pos: 1000

training:
  batch_size: 1
  loss_term_factors:
    generic: 1.
  lr: 3e-4
  lr_decay_factor: 1.
  num_epochs: 1000
